--[[
	iBuffDebuffU Localization
--]]

if ( GetLocale() == "zhCN" ) then
	--special thanks to www.wowui.cn
	
	L_IBDU_SLASHOPT1 = "anchor"
	L_IBDU_SLASHOPT2 = "config"
	L_IBDU_SLASHOPT3 = "on"
	L_IBDU_SLASHOPT4 = "off"
	L_IBDU_SLASH1 = "/ibdu "..L_IBDU_SLASHOPT1.." - 开启锚点"
	L_IBDU_SLASH2 = "/ibdu "..L_IBDU_SLASHOPT2.." - 开启配置窗口"
	L_IBDU_SLASH3 = "/ibdu "..L_IBDU_SLASHOPT3.." - 开启 iBuffDebuffU [ON]"
	L_IBDU_SLASH4 = "/ibdu "..L_IBDU_SLASHOPT4.." - 关闭 iBuffDebuffU [OFF]"
	L_IBDU_ANCHOR = ": 右键点击 (保存)"
	
	L_IBDU_OPT1 = "计时条向上叠加"
	L_IBDU_OPT2 = "使用 HH:MM:SS 格式"
	L_IBDU_OPT3 = "显示法术等级"
	L_IBDU_OPT4 = "显示法术叠加"
	L_IBDU_OPT5 = "显示玩家 buff/debuff 提示讯息"
	L_IBDU_OPT6 = "显示玩家 buff 条"
	L_IBDU_OPT7 = "显示玩家 debuff 条"
	L_IBDU_OPT8 = "隐藏暴雪 buff 框体"
	L_IBDU_OPT9 = "计时条大小和缩放"
	L_IBDU_OPT10 = "使用 Debuff 着色  |cFF99CC33[诅咒, 毒药, 魔法, 疾病]|r"
	L_IBDU_OPT11 = "显示目标 buff 条"
	L_IBDU_OPT12 = "显示目标 debuff 条"
	L_IBDU_OPT13 = "显示焦点 buff 条"
	L_IBDU_OPT14 = "显示焦点 debuff 条"
	L_IBDU_OPT15 = "过滤器"
	L_IBDU_OPT16 = "Show only the buffs cast by the player."
	
	L_IBDU_OPT_SLIDER1 = "缩放"
	L_IBDU_OPT_SLIDER2 = "宽"
	L_IBDU_OPT_SLIDER3 = "高"
	L_IBDU_OPT_SLIDER4 = "字体大小"
	L_IBDU_OPT_SLIDER5 = "计时条透明度"
	L_IBDU_OPT_SLIDER6 = "计时条背景透明度"
	L_IBDU_OPT_SLIDER7 = "字型透明度"
	L_IBDU_OPT_SLIDER8 = "计时条距离"
	L_IBDU_OPT_SLIDER9 = "按时间限制"
	L_IBDU_OPT_SLIDER10 = "Buff 显示计数"
	L_IBDU_OPT_SLIDER11 = "Debuff 显示计数"
	
	L_IBDU_PANEL_1 = "玩家设置"
	L_IBDU_PANEL_2 = "目标设置"
	L_IBDU_PANEL_3 = "焦点设置"
	
	L_IBDU_TAB_1 = "综合"
	L_IBDU_TAB_2 = "设置"
		
elseif ( GetLocale() == "ruRU" )  then

	L_IBDU_SLASHOPT1 = "anchor"
	L_IBDU_SLASHOPT2 = "config"
	L_IBDU_SLASHOPT3 = "on"
	L_IBDU_SLASHOPT4 = "off"
	L_IBDU_SLASH1 = "/xbt "..L_IBDU_SLASHOPT1.." - toggles a movable anchor"
	L_IBDU_SLASH2 = "/xbt "..L_IBDU_SLASHOPT2.." - toggles the configuration window"
	L_IBDU_SLASH3 = "/xbt "..L_IBDU_SLASHOPT3.." - toggles iBuffDebuffU [ON]"
	L_IBDU_SLASH4 = "/xbt "..L_IBDU_SLASHOPT4.." - toggles iBuffDebuffU [OFF]"
	L_IBDU_ANCHOR = ": Right Click (Save)"
	
	L_IBDU_OPT1 = "Grow the bars upward"
	L_IBDU_OPT2 = "Use HH:MM:SS format"
	L_IBDU_OPT3 = "Show spell rank"
	L_IBDU_OPT4 = "Show spell stacks"
	L_IBDU_OPT5 = "Show player buff/debuff tooltips"
	L_IBDU_OPT6 = "Show player buff bars"
	L_IBDU_OPT7 = "Show player debuff bars"
	L_IBDU_OPT8 = "Hide Blizzard buff frames"
	L_IBDU_OPT9 = "Bar Sizing and Scaling"
	L_IBDU_OPT10 = "Use Debuff Coloring  |cFF99CC33[Curse, Poison, Magic, Disease]|r"
	L_IBDU_OPT11 = "Show target buff bars"
	L_IBDU_OPT12 = "Show target debuff bars"
	L_IBDU_OPT13 = "Show focus buff bars"
	L_IBDU_OPT14 = "Show focus debuff bars"
	L_IBDU_OPT15 = "Filters"
	L_IBDU_OPT16 = "Show only the buffs cast by the player."
	
	L_IBDU_OPT_SLIDER1 = "Scale"
	L_IBDU_OPT_SLIDER2 = "Width"
	L_IBDU_OPT_SLIDER3 = "Height"
	L_IBDU_OPT_SLIDER4 = "Font Size"
	L_IBDU_OPT_SLIDER5 = "Bar Alpha"
	L_IBDU_OPT_SLIDER6 = "Bar BG Alpha"
	L_IBDU_OPT_SLIDER7 = "Font Alpha"
	L_IBDU_OPT_SLIDER8 = "Bar Distance"
	L_IBDU_OPT_SLIDER9 = "Limit by Time"
	L_IBDU_OPT_SLIDER10 = "Buff Display Count"
	L_IBDU_OPT_SLIDER11 = "Debuff Display Count"
	
	L_IBDU_PANEL_1 = "Player Settings"
	L_IBDU_PANEL_2 = "Target Settings"
	L_IBDU_PANEL_3 = "Focus Settings"
	
	L_IBDU_TAB_1 = "General"
	L_IBDU_TAB_2 = "Settings"
		
elseif ( GetLocale() == "zhTW" ) then
	--special thanks to www.wowui.cn
	
	L_IBDU_SLASHOPT1 = "anchor"
	L_IBDU_SLASHOPT2 = "config"
	L_IBDU_SLASHOPT3 = "on"
	L_IBDU_SLASHOPT4 = "off"
	L_IBDU_SLASH1 = "/ibdu "..L_IBDU_SLASHOPT1.." - 開啟錨點"
	L_IBDU_SLASH2 = "/ibdu "..L_IBDU_SLASHOPT2.." - 開啟配置窗口"
	L_IBDU_SLASH3 = "/ibdu "..L_IBDU_SLASHOPT3.." - 開啟 iBuffDebuffU [ON]"
	L_IBDU_SLASH4 = "/ibdu "..L_IBDU_SLASHOPT4.." - 關閉 iBuffDebuffU [OFF]"
	L_IBDU_ANCHOR = ": 右鍵點擊 (保存)"
	
	L_IBDU_OPT1 = "計時條向上疊加"
	L_IBDU_OPT2 = "使用 HH:MM:SS 格式"
	L_IBDU_OPT3 = "顯示法術等級"
	L_IBDU_OPT4 = "顯示法術疊加"
	L_IBDU_OPT5 = "顯示玩家 buff/debuff 提示訊息"
	L_IBDU_OPT6 = "顯示玩家 buff 條"
	L_IBDU_OPT7 = "顯示玩家 debuff 條"
	L_IBDU_OPT8 = "隱藏暴雪 buff 框體"
	L_IBDU_OPT9 = "計時條大小和縮放"
	L_IBDU_OPT10 = "使用 Debuff 著色  |cFF99CC33[詛咒, 毒藥, 魔法, 疾病]|r"
	L_IBDU_OPT11 = "顯示目標 buff 條"
	L_IBDU_OPT12 = "顯示目標 debuff 條"
	L_IBDU_OPT13 = "顯示焦點 buff 條"
	L_IBDU_OPT14 = "顯示焦點 debuff 條"
	L_IBDU_OPT15 = "過濾器"
	L_IBDU_OPT16 = "Show only the buffs cast by the player."
	
	L_IBDU_OPT_SLIDER1 = "縮放"
	L_IBDU_OPT_SLIDER2 = "寬"
	L_IBDU_OPT_SLIDER3 = "高"
	L_IBDU_OPT_SLIDER4 = "字體大小"
	L_IBDU_OPT_SLIDER5 = "計時條透明度"
	L_IBDU_OPT_SLIDER6 = "計時條背景透明度"
	L_IBDU_OPT_SLIDER7 = "字型透明度"
	L_IBDU_OPT_SLIDER8 = "計時條距離"
	L_IBDU_OPT_SLIDER9 = "按時間限制"
	L_IBDU_OPT_SLIDER10 = "Buff 顯示計數"
	L_IBDU_OPT_SLIDER11 = "Debuff 顯示計數"
	
	L_IBDU_PANEL_1 = "玩家設置"
	L_IBDU_PANEL_2 = "目標設置"
	L_IBDU_PANEL_3 = "焦點設置"
	
	L_IBDU_TAB_1 = "綜合"
	L_IBDU_TAB_2 = "設置"
		
elseif ( GetLocale() == "frFR" ) then

	L_IBDU_SLASHOPT1 = "anchor"
	L_IBDU_SLASHOPT2 = "config"
	L_IBDU_SLASHOPT3 = "on"
	L_IBDU_SLASHOPT4 = "off"
	L_IBDU_SLASH1 = "/xbt "..L_IBDU_SLASHOPT1.." - toggles a movable anchor"
	L_IBDU_SLASH2 = "/xbt "..L_IBDU_SLASHOPT2.." - toggles the configuration window"
	L_IBDU_SLASH3 = "/xbt "..L_IBDU_SLASHOPT3.." - toggles iBuffDebuffU [ON]"
	L_IBDU_SLASH4 = "/xbt "..L_IBDU_SLASHOPT4.." - toggles iBuffDebuffU [OFF]"
	L_IBDU_ANCHOR = ": Right Click (Save)"
	
	L_IBDU_OPT1 = "Grow the bars upward"
	L_IBDU_OPT2 = "Use HH:MM:SS format"
	L_IBDU_OPT3 = "Show spell rank"
	L_IBDU_OPT4 = "Show spell stacks"
	L_IBDU_OPT5 = "Show player buff/debuff tooltips"
	L_IBDU_OPT6 = "Show player buff bars"
	L_IBDU_OPT7 = "Show player debuff bars"
	L_IBDU_OPT8 = "Hide Blizzard buff frames"
	L_IBDU_OPT9 = "Bar Sizing and Scaling"
	L_IBDU_OPT10 = "Use Debuff Coloring  |cFF99CC33[Curse, Poison, Magic, Disease]|r"
	L_IBDU_OPT11 = "Show target buff bars"
	L_IBDU_OPT12 = "Show target debuff bars"
	L_IBDU_OPT13 = "Show focus buff bars"
	L_IBDU_OPT14 = "Show focus debuff bars"
	L_IBDU_OPT15 = "Filters"
	L_IBDU_OPT16 = "Show only the buffs cast by the player."
	
	L_IBDU_OPT_SLIDER1 = "Scale"
	L_IBDU_OPT_SLIDER2 = "Width"
	L_IBDU_OPT_SLIDER3 = "Height"
	L_IBDU_OPT_SLIDER4 = "Font Size"
	L_IBDU_OPT_SLIDER5 = "Bar Alpha"
	L_IBDU_OPT_SLIDER6 = "Bar BG Alpha"
	L_IBDU_OPT_SLIDER7 = "Font Alpha"
	L_IBDU_OPT_SLIDER8 = "Bar Distance"
	L_IBDU_OPT_SLIDER9 = "Limit by Time"
	L_IBDU_OPT_SLIDER10 = "Buff Display Count"
	L_IBDU_OPT_SLIDER11 = "Debuff Display Count"
	
	L_IBDU_PANEL_1 = "Player Settings"
	L_IBDU_PANEL_2 = "Target Settings"
	L_IBDU_PANEL_3 = "Focus Settings"
	
	L_IBDU_TAB_1 = "General"
	L_IBDU_TAB_2 = "Settings"
		
elseif ( GetLocale() == "koKR" ) then

	L_IBDU_SLASHOPT1 = "anchor"
	L_IBDU_SLASHOPT2 = "config"
	L_IBDU_SLASHOPT3 = "on"
	L_IBDU_SLASHOPT4 = "off"
	L_IBDU_SLASH1 = "/xbt "..L_IBDU_SLASHOPT1.." - toggles a movable anchor"
	L_IBDU_SLASH2 = "/xbt "..L_IBDU_SLASHOPT2.." - toggles the configuration window"
	L_IBDU_SLASH3 = "/xbt "..L_IBDU_SLASHOPT3.." - toggles iBuffDebuffU [ON]"
	L_IBDU_SLASH4 = "/xbt "..L_IBDU_SLASHOPT4.." - toggles iBuffDebuffU [OFF]"
	L_IBDU_ANCHOR = ": Right Click (Save)"
	
	L_IBDU_OPT1 = "Grow the bars upward"
	L_IBDU_OPT2 = "Use HH:MM:SS format"
	L_IBDU_OPT3 = "Show spell rank"
	L_IBDU_OPT4 = "Show spell stacks"
	L_IBDU_OPT5 = "Show player buff/debuff tooltips"
	L_IBDU_OPT6 = "Show player buff bars"
	L_IBDU_OPT7 = "Show player debuff bars"
	L_IBDU_OPT8 = "Hide Blizzard buff frames"
	L_IBDU_OPT9 = "Bar Sizing and Scaling"
	L_IBDU_OPT10 = "Use Debuff Coloring  |cFF99CC33[Curse, Poison, Magic, Disease]|r"
	L_IBDU_OPT11 = "Show target buff bars"
	L_IBDU_OPT12 = "Show target debuff bars"
	L_IBDU_OPT13 = "Show focus buff bars"
	L_IBDU_OPT14 = "Show focus debuff bars"
	L_IBDU_OPT15 = "Filters"
	L_IBDU_OPT16 = "Show only the buffs cast by the player."
	
	L_IBDU_OPT_SLIDER1 = "Scale"
	L_IBDU_OPT_SLIDER2 = "Width"
	L_IBDU_OPT_SLIDER3 = "Height"
	L_IBDU_OPT_SLIDER4 = "Font Size"
	L_IBDU_OPT_SLIDER5 = "Bar Alpha"
	L_IBDU_OPT_SLIDER6 = "Bar BG Alpha"
	L_IBDU_OPT_SLIDER7 = "Font Alpha"
	L_IBDU_OPT_SLIDER8 = "Bar Distance"
	L_IBDU_OPT_SLIDER9 = "Limit by Time"
	L_IBDU_OPT_SLIDER10 = "Buff Display Count"
	L_IBDU_OPT_SLIDER11 = "Debuff Display Count"
		
	L_IBDU_PANEL_1 = "Player Settings"
	L_IBDU_PANEL_2 = "Target Settings"
	L_IBDU_PANEL_3 = "Focus Settings"
	
	L_IBDU_TAB_1 = "General"
	L_IBDU_TAB_2 = "Settings"
	
else

	L_IBDU_SLASHOPT1 = "anchor"
	L_IBDU_SLASHOPT2 = "config"
	L_IBDU_SLASHOPT3 = "on"
	L_IBDU_SLASHOPT4 = "off"
	L_IBDU_SLASH1 = "/xbt "..L_IBDU_SLASHOPT1.." - toggles a movable anchor"
	L_IBDU_SLASH2 = "/xbt "..L_IBDU_SLASHOPT2.." - toggles the configuration window"
	L_IBDU_SLASH3 = "/xbt "..L_IBDU_SLASHOPT3.." - toggles iBuffDebuffU [ON]"
	L_IBDU_SLASH4 = "/xbt "..L_IBDU_SLASHOPT4.." - toggles iBuffDebuffU [OFF]"
	L_IBDU_ANCHOR = ": Right Click (Save)"
	
	L_IBDU_OPT1 = "Grow the bars upward"
	L_IBDU_OPT2 = "Use HH:MM:SS format"
	L_IBDU_OPT3 = "Show spell rank"
	L_IBDU_OPT4 = "Show spell stacks"
	L_IBDU_OPT5 = "Show player buff/debuff tooltips"
	L_IBDU_OPT6 = "Show player buff bars"
	L_IBDU_OPT7 = "Show player debuff bars"
	L_IBDU_OPT8 = "Hide Blizzard buff frames"
	L_IBDU_OPT9 = "Bar Sizing and Scaling"
	L_IBDU_OPT10 = "Use Debuff Coloring  |cFF99CC33[Curse, Poison, Magic, Disease]|r"
	L_IBDU_OPT11 = "Show target buff bars"
	L_IBDU_OPT12 = "Show target debuff bars"
	L_IBDU_OPT13 = "Show focus buff bars"
	L_IBDU_OPT14 = "Show focus debuff bars"
	L_IBDU_OPT15 = "Filters"
	L_IBDU_OPT16 = "Show only the buffs cast by the player."
	
	L_IBDU_OPT_SLIDER1 = "Scale"
	L_IBDU_OPT_SLIDER2 = "Width"
	L_IBDU_OPT_SLIDER3 = "Height"
	L_IBDU_OPT_SLIDER4 = "Font Size"
	L_IBDU_OPT_SLIDER5 = "Bar Alpha"
	L_IBDU_OPT_SLIDER6 = "Bar BG Alpha"
	L_IBDU_OPT_SLIDER7 = "Font Alpha"
	L_IBDU_OPT_SLIDER8 = "Bar Distance"
	L_IBDU_OPT_SLIDER9 = "Limit by Time"
	L_IBDU_OPT_SLIDER10 = "Buff Display Count"
	L_IBDU_OPT_SLIDER11 = "Debuff Display Count"
	
	L_IBDU_PANEL_1 = "Player Settings"
	L_IBDU_PANEL_2 = "Target Settings"
	L_IBDU_PANEL_3 = "Focus Settings"
	
	L_IBDU_TAB_1 = "General"
	L_IBDU_TAB_2 = "Settings"
	
end